### ISSUE TITLE
Organização do código em Java

### ISSUE THREAD

**Issue by kyriosdata** [josecxsta/cs-2019-01#16]
- Há múltiplas classes Number (remova-as). 
- Há muitas classes fora do package com.github.josexcsta.ufg.cs.aula01, ou seja, precisam de package adequado, e não pode ser quadradoPerfeito ou numeroPrimo, por exemplo. Observe como o primeiro está montado, é necessário algo similar, por exemplo, com.github.josexcsta.ufg.cs.aula01.algoritmos.aplicacoes.
- Ainda temos um package "algoritmos" com vários arquivos, ou seja, há múltiplas estratégias de organização do código aqui. Você deve fazer uso exclusivamente de uma, a melhor é aquela baseada em uma classe (Algoritmos) para manter todos os métodos (minha opção para este cenário).

**Comment by josecxsta** [comment]
Optei pela alternativa indicada de deixar os algoritmos na classe Algoritmos
