### ISSUE TITLE
Remova branches (faça o merge antes, claro)

### ISSUE THREAD

**Issue by kyriosdata** [josecxsta/cs-2019-01#6]
Seu repositório possui vários _branches_, o que, neste contexto, não é bom, pois as mudanças em um provavelmente afetam os demais. Dito de outra forma, em uma empresa, quando há uma base de código extensa, alguém trabalha em uma parte, outro trabalha em outra, aqui só há uma parte pequena com múltiplos esforços sobre ela, o que naturalmente resulta em MUITOS conflitos. Você deveria, aqui, estar concluindo tarefa por tarefa e removendo o branch de cada uma delas antes de iniciar a próxima.

**Comment by josecxsta** [comment]
feito!
