### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by kyriosdata** [josecxsta/cs-2019-01#7]
- Está incompleta. Por exemplo, encontrei esta linha de documentação que, naturalmente, diz pouco sobre o que é retornado. Precisamos saber, por exemplo, "verdadeiro quando o CPF satisfaz as regras de formação de um CPF". Linha: ` @returns {boolean} a`. Curiosamente esta linha está no Crivo de Eratóstenes. 
- Nesta implementação lê-se "Calcula o Crivo de Eratostenes dado uma coleção de numeros e um limite.", onde melhor seria algo como "Aplica o método conhecido por Crivo de Er...".
- Também encontrei "Calcula o valor PI de um numero." onde o mais preciso, suponho, seria: "Produz uma aproximação do valor de PI baseado no número de iterações fornecido, onde quanto maior o número de iterações, maior a precisão de PI".
- Não se esqueça de fornecer o nome da variável do parâmetro na documentação. Por exemplo @param {number} numerador o numerador da divisão

**Comment by josecxsta** [comment]
corrigido
