### ISSUE TITLE
Leiaute

### ISSUE THREAD

**Issue by kyriosdata** [josecxsta/cs-2019-01#8]
- Use o recurso do seu editor ou IDE para reformatar o código. Se ele não possui tal recurso, então minha orientação é mudar de ferramenta, pois manualmente ajustar o leiaute vai reduzir sua produtividade.

**Comment by josecxsta** [comment]
Estou usando, único problema que tenho é com o comentário da documentação. Não sei se é no editou ou  na configuração mas quando reformato o código perco os espaços que ficam antes dos asteriscos. Vou corrigir isso.
