### ISSUE TITLE
legibilidade

### ISSUE THREAD

**Issue by kyriosdata** [josecxsta/cs-2019-01#9]
O seguinte trecho foi extraído do código: 
```
const dayValidate = day => (day >= 1 && day <= 31);
const monthValidate = month => (month >= 1 && month <= 12);
const yearValidate = year => (year >= 12 && year <= 1753);
``` 
A implementação é da rotina diaDaSemana. Não seria melhor...
```
function diaValido(dia) {
  return dia >= 1 && dia <= 31;
}
....
```

São semanticamente equivalentes, mas não na perspectiva da manutenção. A alternativa apresentada é mais simples para se detectar eventual falha.

**Comment by josecxsta** [comment]
corrigido! valeu
